builds:
  - binary: go-cacher
    main: ./cmd/go-cacher-s3
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - '6'
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w # Don't set main.version.

archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "go-tool-cache_checksums.txt"
